name: Update Reading List

on:
  schedule:
    - cron: "*/30 * * * *" # every 30 min
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download sheet
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vTNQlxW3g15d0VUUistWJjLUO_7esUJHW5l0_1zj8cUjzjqlPiz8jTBYpLIMXBp8nYT3bFRX4fsWq-v/pub?output=csv" \
          -o data/reading.csv

      - name: Build HTML
        run: |
          python scripts/build_reading_list.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update reading list" || exit 0
          git push
